= Solid-Based Extended Access Control and Traceability in Data-Driven Web-Based Systems (SEACT)
// Refs:
:url-repo: https://github.com/guddii/SEACT

image:https://img.shields.io/badge/Project-Solid-7C4DFF.svg[link="https://solidproject.org/"]
image:https://img.shields.io/github/actions/workflow/status/guddii/SEACT/github-pages.yml[link="{url-repo}/actions/workflows/github-pages.yml"]

This work focuses on improving solid-based extended access control and traceability in data-driven web-based systems.
By implementing an extended access control mechanism and improved traceability of data access, this project aims to strengthen the security and transparency of web applications.
The https://solidproject.org/TR/protocol[Solid Protocol] forms the basis for these enhancements, which aim to provide clear and effective control over access to sensitive data.

In this repository you will find the complete source code, detailed integration instructions and examples of how to use these extensions.
The thesis provides not only a theoretical foundation, but also practical implementations for developers and researchers concerned with privacy and access control in modern web applications.

== Installation

This is a https://nodejs.org/en/download/package-manager[Node.js] based project, please use the package manager https://pnpm.io/installation[pnpm] to install this project.

[source,bash]
----
pnpm install
----

An `.env` file is also required to provide the necessary configurations at runtime.
See xref:.example.env[] for a copyable example of the use of environment variables.

[source,bash]
----
cp .example.env .env
----

If you use a copied version of the environment variables, you must also adjust the hosts in the local environment.

[source]
----
127.0.0.1 client.localhost
127.0.0.1 dpc.localhost
127.0.0.1 proxy.localhost
127.0.0.1 server.localhost
----

== Usage

If you want to run this project in development mode, enter the following command in your terminal:

[source,bash]
----
pnpm run dev
----

The following users are available in development mode:

[width=100%]
|===
|   |email |password

|client
|client@example.com
|secret!

|dpc
|dpc@example.com
|secret!
|===

The accounts are available at http://proxy.localhost:4000/.account/

== Licence

This project is licensed under link:LICENSE[MIT licence].
