= Ownership Verification

If a storage is monitored by a data trustee, who is responsible for maintaining an accurate record of the data, it is necessary to verify the ownership of the data at some point.
This is because there is currently no direct relationship between the WebID and the storage, and the data must be claimed.
The verification can be created either when a <<Data Capturing Strategies, data capture strategy>> (Opt-In) is initiated and the relevant register entry is written, or when the captured data is requested.
Furthermore, the opt-in approach would permit the automated granting of access to the captured data, as the WebID has already been registered.
An alternative approach that is applicable in any situation is to write a verification token and code at the resource location, which is randomly generated by the data trustee.
This approach ensures that the requester has a minimum level of privileges to the data maintained by the data trustee.
It works analogous to other services, such as Google's Search Consolefootnote:[https://support.google.com/webmasters/answer/9008080].
A similar challenge is faced by these services, namely that the <<DNS>> server is only aware of the Domain Name and IP address relationship, but lacks the information necessary to determine the ownership of the domain name (tbd.).