= Problem Definition

As already mentioned, the Solid project is an RDF-based ecosystem that aims to achieve a decentralized web for individuals, organizations, and applications, referred to as agents.
The backbone of the project is the Solid Protocol.
The protocol specifies how agents store their data securely in decentralized data storages, also known as Pods.
These storage systems can be compared to secure, personal web servers for data, such as Dropbox, ownCloud, Nextcloud, or similar software, but with a specified public API.
This interface utilizes WebIDs to identify the agents within the system.
As the storage owner has control over which agents can access it, they can choose to restrict access to only WebIDs, completely restrict access, or make it publicly accessible.

The Solid Community Group has been developing this technological approach since 2018. The ecosystem is currently in its early stages of development, and some specifications are still in draft form.
Therefore, it may lack some features that are highly recommended in productive environments.
This results in the following issues that require attention:

[horizontal,labelwidth=15]
[[ISSUE-1,ISSUE-1]] ISSUE-1:: The Solid protocol only specifies the ability to grant or deny access.
It does not track the actual request for a resource.
[[ISSUE-2,ISSUE-2]] ISSUE-2:: Solid is based on RDF and therefore favors interconnected data, what increased the demand for the stored data.
[[ISSUE-3,ISSUE-3]] ISSUE-3:: There may be changes to existing specifications as they need to be improved or are still in the draft stage.
[[ISSUE-4,ISSUE-4]] ISSUE-4:: The Solid ecosystem will be expanded with newly introduced specifications or APIs.
[[ISSUE-5,ISSUE-5]] ISSUE-5:: New Solid providers are being introduced because of their increasing popularity.

The first and second issues describe the need for traceability to control access to one's own data.
A general problem with updates is addressed by the third through fifth issues.
However, all of these concerns will affect the goals of this research.
