= Technology Stack

The technological stack is entirely based on ECMAScript respectively TypeScript.
Server-side scripts will be executed in the Node.js runtime environment, while client-side scripts will utilise the corresponding engine of the browser.
A variety of packages are utilised in the experimental prototype, with two packages of particular significance for this study: the Community Solid Serverfootnote:[https://communitysolidserver.github.io/] and Inrupt JavaScript Client Librariesfootnote:[https://docs.inrupt.com/developer-tools/javascript/client-libraries/].

The *Community Solider Server* is a modular implementation of the Solid Protocol, which allows for a variety of configuration options due to its modularity.
With the exception of the configurations that must be changed for the <<Experiments>>, the default configurations have been applied, as generated by the Community Solider Server configuration generatorfootnote:[https://communitysolidserver.github.io/configuration-generator/v7/].
The configuration options that have a particular influence on the tested scenario are data management and account management options.
The data storage component of data management is configured as the file system by default, which may have an impact on performance due to the necessity of writing files to the hard drive.
Similarly, locks are stored in the file system and are used to prevent simultaneous write operations on the same resource.
The default authorization mechanism is <<WAC>>.
With regard to account management, it is important to note that suffixes are used as storage container URLs, rather than subdomains.
Furthermore, account management includes the identity provider, which uses <<OIDC>>.
The complete configuration file can be accessed in xref:css_configuration[xrefstyle=short].


At the client side, the *Inrupt JavaScript Client Library* is used to access RDF resources in a uniformed way.
Consequently, it is almost impossible to use <<CSS>> vendor <<API, APIs>>.

The network protocol <<HTTP>> is employed for all operations in this research.
Security measures such as <<HTTPS>> are not considered in this analysis.
Similarly, the Solid provider has not been tested in an isolated network with a proxy, which must be the only public-accessible instance for a secure run in production environments.
This potential issue has been tested with Dockerfootnote:[https://docs.docker.com/], but it did not affect the research scenario.
