### Get claims for first user (client) from registry
GET http://proxy.localhost:4000/dpc/registries
Authorization: Bearer {{$auth.token("dpc")}}
Accept: application/ld+json

> {%
    client.global.set("verificationResource", response.body[0]["urn:claim#verificationResource"][0]["@id"]);
    client.global.set("verificationCodeDPC", response.body[0]["urn:claim#verificationCode"][0]["@value"]);
%}

### Get the token from client storage
GET {{verificationResource}}
Authorization: Bearer {{$auth.token("dpc")}}
Accept: application/ld+json

> {%
    client.global.set("verificationCodeClient", response.body[0]["urn:claim#verificationCode"][0]["@value"]);

    client.test("Compare token", function () {
        client.assert(client.global.get("verificationCodeDPC") === client.global.get("verificationCodeClient"), "Token are not equal");
    });
%}