### Get Log Vocab
GET http://proxy.localhost:4000/dpc/ns/log

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Log Shex
GET http://proxy.localhost:4000/dpc/ns/shex/log

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Log ShapeTree
GET http://proxy.localhost:4000/dpc/ns/tree/log

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}