### Read a WebID
GET http://localhost:4000/client/profile/card

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}

### Read a WebID Metadata
GET http://localhost:4000/client/profile/card.meta

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}
