@startuml
component "Solid app" as client
interface "Internet" as internet
component "Private Network" {
    port "Public Port" as port
    component "Reverse proxy" as proxy
    interface "IdMS" as idms
}
component "Web server" as server

client -right-( internet
internet -right- server
internet -- port
port -- proxy
proxy -right-( idms 
@enduml