@startmindmap
* Solid
-- Integration
---_ Integrationsmuster
---_ Datenhaltung 
----_ Anzahl Pods
----_ Transitive anfragen 
'(4pods, 3pods, 2pods Datenhaltung; Flußkontrolle)
---_ Ergänzende Authentisierung / Authentifizierung 
-- Anwendung
---_ Datenschutzcockpit
'----_ Netzwerk Proxy / Mediator
---_ Kollaboration
-- Benutzererfahrung
---_ Generischer Editor
---_ Semantisches UI Vocabular
++ Daten Transformation
+++_ SPARQL Endpunkt
+++_ Versionierung
+++_ Datenmigration
+++_ Modellgetriebene Entw.
'++++_ E/A über Fremdsysteme
'++++_ Solid als Datenquelle
'++++_ Minimalitätsbedingung
++ Netzwerk Proxy / Mediator
+++_ Logging
+++_ Debugging
+++_ Access Requests and Grants
+++_ Protokoll
@endmindmap