### Create a turtle file
POST http://localhost:4000/pod1/
Authorization: Bearer {{$auth.token("proxy")}}
Content-Type: text/turtle
Slug: myFile2

<ex:s> <ex:p> <ex:o>.

### Retrieve a turtle file
GET http://localhost:4000/pod1/myFile2
Authorization: Bearer {{$auth.token("proxy")}}
Content-Type: text/turtle

### Deleting resources
DELETE http://localhost:4000/pod1/myFile2
Authorization: Bearer {{$auth.token("proxy")}}