@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Authorization Client Credentials Flow ( ""agent"" )
autonumber 1 1 "<b>[0]"

participant "Proxy" as Proxy
participant "Server" as Server

    [->     Proxy       ++  : **POST** Request ""agent"" authorization token
ref over Proxy, Server      : Forwarded Request
    [<--    Proxy       --  : ""Agent"" authorization token
@enduml