@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** DPC Middleware
autonumber 1 1 "<b>[0]"

participant "Proxy" as Proxy
participant "Server" as Server

ref over Proxy, Server  : Authorization Client Credentials Flow ( DPC )
opt isDpcAgentLoggedIn
loop hasContainerResources
    Proxy   ->  Proxy   : <b>HEAD</b> Request closest container resource
ref over Proxy, Server  : Forwarded Request
    break existStorageInResponseHeader
    Proxy   -> Proxy        : Lookup claim data in registry by storage
    ref over Proxy, Server  : Forwarded Request
    Proxy   -> Proxy        : Set base url from registry claim data
    end

end
opt existStorage
||5||
ref over Proxy, Server : Access Log Update ( "/accessLog" )
end
end
@enduml