@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** DPC Claim Registry
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

ref over DPC_API,Proxy,Server           : Authorization Client Credentials Flow ( DPC )
DPC_API     ->  Proxy               ++  : **GET** List of claimed storages\nfor a given WebID
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy               --  : DPC storage and verification key pairs

@enduml