@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Forwarded Request
autonumber 1 1 "<b>[0]"

participant "Proxy" as Proxy
participant "Server" as Server

        [->  Proxy  ++  : **CRUD** Request
        opt isLoggableRequest
        ||5||
        ref over Proxy, Server : DPC Middleware
        end
Proxy   ->  Server  ++  : **CRUD** Request
Proxy   <-- Server  --  : Server response
        [<-- Proxy  --  : Server response

@enduml