@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Get Claimed Resource ( ""resource"" )
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

ref over DPC_API,Proxy,Server           : Authorization Client Credentials Flow ( DPC )
ref over DPC_API,Proxy,Server           : Lookup Claim Data in Registry


DPC_API     ->  Proxy                ++  : **GET** Verification code from verification resource
ref over Proxy, Server                  : Forwarded Request
note over Proxy, Server
DPC agent must have
read permissions
end note
DPC_API     <-- Proxy                --  : Verification code

opt equivalentVerificationCodes
DPC_API     ->  Proxy                 : **GET** the requested ""resource"" from claim data path
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                 : Any response
end
@enduml