@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Get Claimed Resource ( ""resource"" )
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

ref over DPC_API,Proxy,Server           : Authorization Client Credentials Flow ( DPC )
DPC_API     ->  Proxy                ++  : **GET** Claims from registry
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                --  : Dataset with verification codes

DPC_API     ->  Proxy                ++  : **GET** Verification code from clients' storage
ref over Proxy, Server                  : Forwarded Request
note over Proxy, Server
DPC agent must have
read permissions
end note
DPC_API     <-- Proxy                --  : Verification code

opt equivalent verification codes
DPC_API     ->  Proxy                 : **GET** the requested ""resource"" (in storage)
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                 : Any response
end
@enduml