@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Get Claimed Resource ( ""resource"" )
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

ref over DPC_API,Proxy,Server           : Authorization Client Credentials Flow ( DPC )
DPC_API     ->  Proxy                ++  : **GET** Claims by WebID from registry
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                --  : Turtle reference
DPC_API     ->  Proxy                ++  : **GET** Verification and storage from claim
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                --  : Verification and storage
DPC_API     ->  Proxy                ++  : **GET** Verification from clients' storage
ref over Proxy, Server                  : Forwarded Request
note over Proxy, Server
DPC agent must have
read permissions
end note
DPC_API     <-- Proxy                --  : Verification code and storage
DPC_API     ->  Proxy               ++  : **GET** List of claimed storages\nfor a given WebID
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy               --  : DPC storage and verification key pairs
opt equivalent verification keys
DPC_API     ->  Proxy                 : **GET** the requested ""resource"" (in storage)
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy                 : Turtle response
end
@enduml