@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Initialize a Verification Code
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

DPC_API     ->  DPC_API                 : Generate verification code
ref over DPC_API,Proxy,Server           : Write Verification Code to Client Storage
opt noPreviousErrors
||5||
ref over DPC_API,Proxy,Server           : Write Verification Code to DPC Storage
end
@enduml