@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

autonumber 1 1 "<b>[0]"
mainframe **sd** Authorised CRUD Requests

participant "Client" as Client
participant "Proxy" as Proxy
participant "Server" as Server

ref over Client,Proxy,Server    : Authorization Client Credentials Flow ( CLIENT )
Client  ->  Proxy   ++          : **CRUD** Request
ref over Proxy, Server          : Forwarded Request
Client  <-- Proxy   --          : Forwarded server response
@enduml