@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Set Agent Read Access  ( ""resource"" )
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server

DPC_API  ->  Proxy               ++  : **PUT** ""Resource"" read permissions for a given WebID
ref over Proxy, Server               : Forwarded Request
DPC_API  <-- Proxy               --  : Response
@enduml