@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Write Token to Client Storage
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server


DPC_API  ->  Proxy               ++  : **PUT** Verification token to the storage to be claimed
ref over Proxy, Server               : Forwarded Request
DPC_API  <-- Proxy               --  : Success response
DPC_API  ->  Proxy               ++  : **PUT** Verification token read permissions for DPC agent
ref over Proxy, Server               : Forwarded Request
DPC_API  <-- Proxy               --  : Success response

@enduml