@startuml
'https://plantuml.com/sequence-diagram

skinparam sequenceReferenceBackgroundColor white

mainframe **sd** Write Token to DPC Storage
autonumber 1 1 "<b>[0]"

participant "DPC API" as DPC_API
participant "Proxy" as Proxy
participant "Server" as Server


ref over DPC_API,Proxy,Server           : Authorization Client Credentials Flow ( DPC )
DPC_API     ->  Proxy               ++  : **PUT** New folder for claim data
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy               --  : Turtle reference
DPC_API     ->  Proxy               ++  : **GET** Registries
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy               --  : Dataset
DPC_API     ->  Proxy               ++  : **PUT** New claim entry to registry
ref over Proxy, Server                  : Forwarded Request
DPC_API     <-- Proxy               --  : Turtle reference
@enduml