= Access Control and Traceability

*Access Control* represents one of the primary use cases of the Solid Protocol, which utilizes Authentication and Authorization as described in the previous section.
It primarily concerns the granting and revocation of access privileges, with the objective of providing a systematic response to the question of who is permitted to perform which actions at which locations and times cite:[fischer_lexikon_2011].

*Traceability*, is defined in two distinct ways.
On the one hand, it can be understood as a step-by-step examination of a program during troubleshooting.
Alternatively, as in the case examined in this work, it refers to the tracing of a route of data in communication.
However, it should be noted that there is no uniform specification that allows for this definition to be universally applied (ibid.).

Extending access control and traceability means enabling an option that allows the tracing of a route of data.
This allows users to have greater control of the exposed data and access privileges given.
This should, in general, enhance access control, which might become obscured in a growing decentralized and highly connected ecosystem.