= Architecture

include::partials/Attributes.adoc[]

include::partials/Preface.adoc[]

<<<

include::partials/Glossary.adoc[leveloffset=+1]

include::partials/Acronyms.adoc[leveloffset=+1]

== System Behavior

This section describes the system behavior using <<UML>> 2.5 with https://plantuml.com/de/[PlantUML] as the generator.
The dynamic behavior of the system's objects will be illustrated with sequence diagrams and other interaction diagrams (sd).

=== Entries

==== Authorised CRUD Requests

The process of authorizing a request can be divided into two steps.
Firstly, an authorization token will be requested using a Client Credentials Flow as defined in https://datatracker.ietf.org/doc/html/rfc6749#section-4.4[RFC 6749], although other authorization processes are also possible.
Secondly, the CRUD request will be sent with an authorization header and the response will be provided accordingly.
The key difference is that the request and response will be forwarded by the proxy instance.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of an authorized CRUD request
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Request_a_resource.puml[]
....

==== Log Claiming

Network logs are captured by storage, not by WebID, and it is necessary to associate the data with a WebID at some point to make it readable to the owner.
This is done by a claiming mechanism.
This requires a solid application that has access to both the user storage and the DPC storage.
Both connections are handled by the DPC API server, and when the connections are established, the API schedules an auth token on behalf of the client agent to be verified by the DPC API server when it discovers the logs.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the log claiming process
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Log_claiming.puml[]
....

==== Log Discovery

The logs in the DPC API server are represented as routes.
These routes will either return an empty turtle file or attempt to resolve the scheduled claim and receive the actual files from the claimed storages.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the discovery of logs
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Log_discovery.puml[]
....

=== References

==== Authentication with Client Credentials

To obtain the authorization token, send a POST request to the authorization server with the client ID and secret in the authentication header.
It is also necessary to set the grant type to `client_credentials` and the scope to `webid`.
The proxy will forward requests as every CRUD request because the authorization server is not directly accessible.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the authentication using client credentials
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Authentication_with_Client_Credentials.puml[]
....

==== Forwarded Request

Request forwarding is quite simple, the proxy receives a CRUD request that is passed through the server.
The returning server response will take the path back to the original requester.
Since the requester can be the proxy itself, there needs to be some kind of guard to prevent infinite recursive calls.
If the requester is someone other than the proxy, the Data Privacy Cockpit middleware can be executed.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the request being forwarded by the proxy
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Forwarded_request.puml[]
....

==== Data Privacy Cockpit Middleware

The Data Privacy Cockpit is a Solid application that requires a dedicated agent and client credentials.
The agent must log in before any other actions can be executed.
If successful, the container resources of the requested resource will be searched until the corresponding storage is found or no more container resources are left to search.
If a storage is found, access logs will be created or updated, with one resource for each RDF class:

- https://www.w3.org/TR/HTTP-in-RDF10/#ResponseClass
- https://www.w3.org/TR/HTTP-in-RDF10/#RequestClass
- https://www.w3.org/TR/HTTP-in-RDF10/#ConnectionClass

The log resources will be grouped by the storage they belong to and owned by the DPC agent.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the Data Privacy Cockpit middleware
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_DPC_middleware.puml[]
....

==== Access Log Update

The update to the access log begins with a test to determine if the resource already exists on the server.
If it does, it will be received as a dataset.
Otherwise, a new dataset will be created.
The dataset will be enriched with new log data and stored on the server.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of an access log resource update
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Access_log_update.puml[]
....

==== Schedule a Token

To schedule a verification token, start by generating a random key.
The DPC API will then store the token, storage, and WebID in a location accessible to the DPC agent for later verification.
If the DPC API cannot access the client's storage, the process will terminate without adding data to the DPC storage.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of scheduling a token
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Schedule_a_token.puml[]
....

==== Write Token to Client Storage

Writing the verification token consists of two steps.
The first step is to write the token to the client's storage.
Since the token must be read by the DPC agent, the second step is to grant read permissions.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of writing a verification token to the clients' storage
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Write_token_to_client_storage.puml[]
....

==== Write Token to DPC Storage

Before writing the token to the DPC storage, the agent must first verify their identity.
After authorization, a new claim containing the verification token and associated storage will be added to the list of claims, along with the WebID-related claims in the registry.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of writing a verification token to the DPC storage
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Write_token_to_dpc_storage.puml[]
....

==== Get Claimed Resource

The process of obtaining a claimed resource will be managed by the DPC agent.
The WebID from the active client session will be used to retrieve the claims from the registry, along with the storage and verification token for that claim.
The DPC agent will then retrieve the verification token from the storage.
If both verification tokens match, the request will be forwarded by the DPC agent.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of how to get a claimed resource
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Get_claimed_resource.puml[]
....


