= Architecture

include::partials/Attributes.adoc[]

include::partials/Glossary.adoc[leveloffset=+1]

include::partials/Acronyms.adoc[leveloffset=+1]

== System Behavior

This section describes the system behavior using <<UML>> 2.5 with https://plantuml.com/de/[PlantUML] as the generator.
The dynamic behavior of the system's objects will be illustrated with sequence diagrams and other interaction diagrams (sd).

=== Authorised CRUD Requests

The process of authorizing a request can be divided into two steps.
Firstly, an authorization token will be requested using a Client Credentials Flow as defined in https://datatracker.ietf.org/doc/html/rfc6749#section-4.4[RFC 6749], although other authorization processes are also possible.
Secondly, the CRUD request will be sent with an authorization header and the response will be provided accordingly.
The key difference is that the request and response will be forwarded by the proxy instance.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of an authorized CRUD request
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Request_a_resource.puml[]
....

=== Authentication with Client Credentials

To obtain the authorization token, send a POST request to the authorization server with the client ID and secret in the authentication header.
It is also necessary to set the grant type to `client_credentials` and the scope to `webid`.
The proxy will forward requests as every CRUD request because the authorization server is not directly accessible.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the authentication using client credentials
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Authentication_with_Client_Credentials.puml[]
....

=== Forwarded Request

Request forwarding is quite simple, the proxy receives a CRUD request that is passed through the server.
The returning server response will take the path back to the original requester.
Since the requester can be the proxy itself, there needs to be some kind of guard to prevent infinite recursive calls.
If the requester is someone other than the proxy, the Data Privacy Cockpit middleware can be executed.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the request being forwarded by the proxy
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Forwarded_request.puml[]
....

=== Data Privacy Cockpit Middleware

The Data Privacy Cockpit is a Solid application that requires a dedicated agent and client credentials.
The agent must log in before any other actions can be executed.
If successful, the container resources of the requested resource will be searched until the corresponding storage is found or no more container resources are left to search.
If a storage is found, access logs will be created or updated, with one resource for each RDF class:

- https://www.w3.org/TR/HTTP-in-RDF10/#ResponseClass
- https://www.w3.org/TR/HTTP-in-RDF10/#RequestClass
- https://www.w3.org/TR/HTTP-in-RDF10/#ConnectionClass

The log resources will be grouped by the storage they belong to and owned by the DPC agent.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the Data Privacy Cockpit middleware
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_DPC_middleware.puml[]
....

=== Access Log Update

The update to the access log begins with a test to determine if the resource already exists on the server.
If it does, it will be received as a dataset.
Otherwise, a new dataset will be created.
The dataset will be enriched with new log data and stored on the server.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of an access log resource update
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Access_log_update.puml[]
....

=== Log Claiming

Network logs are captured by storage, not by WebID, and it is necessary to associate the data with a WebID at some point to make it readable to the owner.
This is done by a claiming mechanism.
This requires a solid application that has access to both the user storage and the DPC storage.
Both connections are handled by the DPC API server, and when the connections are established, the API schedules an auth token on behalf of the client agent that is to be verified by the DPC API server.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the log claiming process
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Log_claiming.puml[]
....

=== Schedule a Token

When scheduling a verification token, a random key must first be generated.
Since the DPC API has an active connection to the client storage, it will store the token there.
In addition, the token and WebID must be stored somewhere that is accessible to the DPC agent, to verify their equality in later processes.
To verify the status of this process, it is set to `scheduled`.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of scheduling a token
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Schedule_a_token.puml[]
....

=== Write Token to Client Storage

Writing the verification token consists of two steps.
The first step is to write the token to the client's storage.
Since the token must be read by the DPC agent, the second step is to grant read permissions.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of writing a verification token to the clients' storage
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Write_token_to_client_storage.puml[]
....

=== Set Claim Status

When setting the claim status, a specific entry, from the registry of claims, will be patched.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of setting the claim status
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Set_claim_status.puml[]
....

=== Verify Token

Verifying a token requires an existing client connection.
The DPC API will look up the tokens associated with the WebID of the current session.
Meanwhile, the access token is requested from the store of the WebID.
If both tokens match, the read privileges for the logging resources are extended by the session's WebID and the status is set to `verified`.
If the tokens do not match, the request is `rejected`.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the verification of a token
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Verify_token.puml[]
....

=== DPC Claim Registry

A claim registry lookup requires an authorized session of a DPC agent.
If this is the case, the persisted storage and verification pairs can be requested for a given WebID.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of a claim registry look up
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_DPC_claim_registry.puml[]
....

=== Set Agent Read Access

This process describes the process of patching the access permission of the client of the current session.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of a resource permission update
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Set_agent_read_access.puml[]
....

=== Log Discovery

The access logs of the storages associated with a WebID can be easily queried with an authorized request to the DPC Claim Registry.

.<<UML>> 2.5.1footnote:uml[https://www.omg.org/spec/UML/2.5.1] Sequence diagram of the discovery of logs
[.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/sd_Log_discovery.puml[]
....