= Data Model

include::partials/Attributes.adoc[]

include::partials/Preface.adoc[]

<<<

include::partials/Glossary.adoc[leveloffset=+1]

include::partials/Acronyms.adoc[leveloffset=+1]

include::partials/Namespaces.adoc[leveloffset=+1]


== Information Engineering

The Solid Specification outlines the overall framework of the system-wide data model.
Additionally, the Solid Application Interoperability Specificationfootnote:[https://solid.github.io/data-interoperability-panel/specification/], an extension to the Solid ecosystem, will be utilised to achieve an application-independent design and a uniform mechanism for data discovery.
It should be noted that the Specification has not yet been fully matured or implemented by any Solid Provider.
However, it can be used in part.
The Editor's Draft of November 7th, 2023 introduces a mechanism for discovering registered data without requiring knowledge of the physical structure of the file system or <<HTTP>> endpoints.
An application only needs to be aware of the profile document and follow the suggested references in the specification.
xref:dm_Logical_model[xrefstyle=short] illustrates these entities and relations.

The Entity-Relationship model uses Clive Finkelstein's <<IE>> notation.
This format is clear and easy to comprehend, making it appropriate for gaining a broad understanding of the logical concept.
To gain a deeper understanding of the information structure in an <<RDF>> context, <<Namespaces>> have been added to the entity names, as well as entity types in double angle brackets: <<Dataset>>, <<Thing>>, and <<ShEx>>.

.<<IE>> diagram of the logical data model
[#dm_Logical_model,.text-center]
[plantuml,format=svg]
....
include::resources/diagrams/dm_Logical_model.puml[]
....

As previously mentioned, the model meets the requirements of the Solid Application Interoperability Specification.
The profile document declares an `interop:Agent`, which refers to a registry set.
This declaration informs agents that the data model will be modelled according to the specification.
The registry set contains a list of all references to data registrations.
A data registration is a resource container that contains all resources in a given treefootnote:[https://shapetrees.org/TR/specification/] and shapefootnote:[https://shex.io/shex-semantics/].
For more information on this data modeling, please consult to the specification.

As the interoperability specification does not address the handling of multi-agent data or require agents to participate in the specification, some enhancements have been made to the data model.
In xref:dm_Logical_model[xrefstyle=short], the highlighted additions (bold) to the model include the requirement that <<Thing, Things>> contained by the registry set must have a unique identifier based on the claimed item, which in this case is the hashed (SHAKE256) storage <<URL>>.
The <<Thing, Thing's>> type is claim:Registry, a newly introduced <<RDF>> vocabulary.
This vocabulary includes the following terms:

* Trustee: The WebID reference of the agent requesting access to the claimed data
* Monitored storage: The observed storage reference
* Verification resource: The reference to the verification resource in the monitored storage.
* Verification Code: A random hash
* Claimed data: The reference to the resource container of all claimed data resources

The `claim:Verification` is a resource within the observed storage that serves to verify using a verification code.
This code must correspond to the verification code within the `claim:Registry` to authorize the trustee's access to the claimed data.
