= Master-Thesis Exposé
:author: Florian Gudat <florian.gudat@guices.com>
:revnumber: v1.0
:revdate: 2023-11-08
:revremark: Leipzig
:library: Asciidoctor
:idprefix:
:numbered:
:toc: macro
:toc-title:
:css-signature: github

Version:: 
{revnumber}, {revdate} ({revremark})

Editors:: 
{author}

Modul (Modulnummer):: 
Mastermodul 
C533.2 Pflichtmodul

Modulverantwortlicher:: 
Prof. Dr.-Ing. Jean-Alexander Müller

Betreuer::
Prof. Dr. Andreas Both

Institut::
Hochschule für Technik, Wirtschaft und Kultur Leipzig 

Fakultät::
Informatik und Medien

[discrete]
== Inhaltsverzeichnis
toc::[]

== Einleitung

// Darstellung des Themas 

Die Solid-Spezifikation macht es möglich, Daten sicher in dezentralen Datenspeichern abzulegen.
Diese Daten können hierbei an ausgewählte Identitäten (Personen, Organisationen oder Anwendungen) über das Internet freigegeben werden.
Die Freigabeinformationen sind an die Daten gekoppelt und dementsprechend auch dezentral organisiert.
Sowohl die Daten als auch die Freigabeinformationen haben eine Identität als Eigentümer, der diese Inhalte verwaltet.

Solid-Server implementieren die serverseitigen Spezifizierungen und Anforderungen der Solid-Spezifikation.
Sie können als eigene Instanz gehostet, oder über öffentliche Anbieterfootnote:[https://solidproject.org/users/get-a-pod#get-a-pod-from-a-pod-provider], genutzt werden.
Hierdurch erfüllen Sie die Aufgaben eines Identity-Management-Systems in einer dezentralen Infrastruktur.

Das zu bearbeitende Thema der Arbeit ist ein Dienst, welcher es möglich macht, die Informationen aus Anfragen, die die Solid-Spezifikation erfüllen, auszulesen, auszuwerten und gegebenenfalls zu modifizieren.
Dies soll unabhängig von der Art des Hostings und der Implementierung des Solid-Servers möglich sein.
Um dies zu erreichen, wird ein Reverse-Proxyfootnote:[https://www.cloudflare.com/de-de/learning/cdn/glossary/reverse-proxy/] als Mediator implementiert, welcher eine generische Verarbeitung von Anfragen erlaubt, um repetitive Prozesse zu vereinheitlichen.
Als Beispiel einer solchen Implementierung wird ein Datenschutzcockpit umgesetzt, welches das Compliance & Auditfootnote:[https://www.internet-sicherheit.de/forschung/forschungsprojekte/abgeschlossene-forschungsprojekte/identity-management/idm-referenzmodell/compliance-audit/] des Identity-Management-Referenzmodellsfootnote:[https://www.internet-sicherheit.de/forschung/forschungsprojekte/abgeschlossene-forschungsprojekte/identity-management/idm-referenzmodell/] bedient.
Hierfür werden die Aufgaben des Compliance-Managements, Monitoring, Reporting und Auditing für den Eigentümer zugänglich gemacht.

// Begründung/Motivation

Das Problem bei dezentralen Systemen ist, dass der Überblick über die Ablagen, insbesondere bei wachsendem Datenbestand, verloren geht.
Bei freigegebenen Daten ist dies problematisch, da gegebenenfalls unwissentliche Zugriffe auf diese Daten möglich sind, obwohl dies vom Eigentümer nicht oder nicht mehr gewünscht ist.
Dies motiviert den Schutz der sensiblen Daten, Revision von Berechtigungen und Revision von Administrationstätigkeiten im Rahmen des Compliance-Managements sowie ein stetiges Monitoring und Reporting der Zugriffe. Diese Funktionen sind durch die Solid-Spezifikation nicht abgedeckt und müssen ergänzt implementiert werden.

Im Rahmen einer Showcase-Implementierung für ein E-Governance-Verfahren footnote:[https://github.com/guddii/showcase-solid-egovernance/] war auffällig, dass auch die Information zur Autorisierung einer Identität verloren geht und jedes Mal neu ausgeführt wird. Das dort genutzte Verfahren zur Autorisierung ist eine Inrupt spezifische Lösung und nur in der Unternehmenslösung des Solid-Servers implementiert.

Die beiden Problemstellungen sollen zeigen, dass es eine generische Lösung benötigt, um auf die individuellen Probleme der jeweiligen softwaretechnischen Lösung zu reagieren und diese bei Bedarf erweitern zu können. 

// Relevanz

== Zielsetzung  

- Ziel der Arbeit und Erkenntnisinteresse herausstellen
- Ergebnisse skizzieren

== Forschungsstand

- Stand der aktuellen Forschung
- zentrale Theorien des Themas

== Forschungskonzept

- Forschungsfrage(n)
- Hypothesen
- Methodik + Begründung
- Daten
- evtl. benötigte Mittel

== Vorläufige Gliederung

Vorläufige Gliederung zur Strukturierung

== Zeitplan

Tabellarische Darstellung der Zeitplanung deiner Masterarbeit (dient als Orientierung und hilft, Probleme frühzeitig zu erkennen)

[bibliography]
== Literaturverzeichnis
bibliography::[]
