= Serialized Data Model

Before looking at the serialized model, it is important to understand the structure of the <<HTTP>> endpoints.
The storage URLs for the <<HTTP>> <<API, APIs>> will begin with a storage identifier added as a suffix to the base <<URL>>.
xref:wbs_Endpoint_structure[xrefstyle=short] shows the storage <<URL, URLs>> at the second level.
The data of the corresponding agent will be represented below this node.

.The structure of the <<HTTP>> endpoints
[.text-center]
[plantuml,format=svg,id="wbs_Endpoint_structure"]
....
include::resources/diagrams/wbs_Endpoint_structure.puml[]
....

The two most commonly used serialization formats for <<RDF>>-based data in data-driven web-based systems are `text/turtle` and `application/ld+json`.
This inspection does not focus on data storage, as the Solid provider is considered replaceable.
However, <<HTTP>> <<API, APIs>> use Turtle as the exchange format for communication, which will be displayed below.
As part of the structural hierarchy shown in xref:wbs_Endpoint_structure[xrefstyle=short], all resources and listings refer to the data model shown in xref:dm_Claim[xrefstyle=short].

== Personal Profile Document (Data Model)

To participate in the Solid Application Interoperability Specification, an `interop:Agent` must be declared in the profile document.
The node will refer to the <<Registry Set (Data Model), registry set>> that contains the references to the registered data.

.`interop:Agent` <<Thing>> at http://example.tld/dpc/profile/card
[source,turtle]
----
include::resources/dump/model/dpc/profile/card$.ttl[lines=14..17]
----

<1> Declaration as `interop:Agent`.
<2> Reference to the registry set.

NOTE: Followed Path [1]

== Registry Set (Data Model)

The registry set contains an entry for each agent who has claimed data captured by the <<DPC>> agent.
This captured data will be referred to as <<Data Registration (Data Model), data registration>>.

The subject of the RDF triple, however, must be unique and built based on the claimed subject.
In this case, it will be the hashed storage <<URL>>.

.`interop:DataRegistry` <<Thing>> at http://example.tld/dpc/registries
[source,turtle]
----
include::resources/dump/model/dpc/registries$.ttl[lines=3..6]
----

<1> The hashed (SHAKE256) storage <<URL>>.

NOTE: Followed Path [1,1]

== Data Registration (Data Model)

The Shape Tree data is referenced in the data registration.
As it is a container resource (see <<Container (Access Logs from Data Model)>>), all child resources will satisfy the <<Shape Trees (Data Model), referenced Shape Tree>>.

.`interop:DataRegistration` <<Thing>> at http://example.tld/dpc/data/74242fac/AccessLog/
[source,turtle]
----
include::resources/dump/model/dpc/data/74242fac/AccessLog/index.ttl[lines=7..11]
----

<1> The referenced Shape Tree.

NOTE: Followed Path [1,1,1], [1,2,1,1]

== Shape Trees (Data Model)

Both Shape Trees, `AccessLogRegistrationTree`, and `AccessLogTree` define the contents of the referring <<container_resource>>.
The `AccessLogRegistrationTree` defines the resources that contain Shape Tree Resources in a given shape.
The <<Shape Expression (Data Model), referenced Shape Expression>> declares the form of the shape.

.Shape Tree at http://example.tld/dpc/ns/log.tree
[source]
----
include::resources/dump/model/dpc/ns/log.tree[]
----

<1> The internal reference to `AccessLogTree`
<2> The reference to the <<Shape Expression (Data Model)>>

NOTE: Followed Path [1,1,1], [1,2,1,1]

== Shape Expression (Data Model)

<<ShEx>> defines the schema for every literal associated with a predicate of the vocabulary.
The RDF vocabulary will not be listed further.

.Shape Expression
[source]
----
include::resources/dump/model/dpc/ns/log.shex[]
----

NOTE: Followed Path [1,1,1], [1,2,1,1]

== Container (Access Logs from Data Model)

As explained in the <<Data Registration (Data Model)>> section, this container resource corresponds to the `interop:DataRegistration` definition.
The files contained within it meet the specified definitions.
For example, the file dated 2024-04-02 will be referred to as <<Access Log (Data Model)>>, matching the <<Shape Expression (Data Model)>>.

.`ldp:Container` <<Thing>> at http://example.tld/dpc/data/74242fac/AccessLog/
[source,turtle]
----
include::resources/dump/model/dpc/data/74242fac/AccessLog/index.ttl[lines=13..14]
include::resources/dump/model/dpc/data/74242fac/AccessLog/index.ttl[lines=23..23]
----

NOTE: Followed Path [1,1,2], [1,2,2]

== Access Log (Data Model)

The access log is a resource that contains the actual data and satisfies the shape as defined in the <<Shape Expression (Data Model)>>.

.`ldp:Container` <<Thing>> at http://example.tld/dpc/data/74242fac/AccessLog/2024-04-02
[source,turtle]
----
include::resources/dump/model/dpc/data/74242fac/AccessLog/2024-04-02$.ttl[]
----

NOTE: Followed Path [1,1,2], [1,2,2]

== Claim Registry (Data Model)

The claim registry is an custom extension of the `interorp:DataRegistry` within the <<Registry Set (Data Model), registry set>>.
It refers to the root container for <<Container (Claimed Data from Data Model), claimed data>> and the <<Verification (Data Model), verification resource>>.

.`claim:Registry` <<Thing>> in at http://example.tld/dpc/registries
[source,turtle]
----
include::resources/dump/model/dpc/registries$.ttl[lines=7..14]
----

NOTE: Followed Path [1,2]

== Container (Claimed Data from Data Model)

This resource contains all claimed data.
When using the Solid Application Interoperability Specification, it primarily refers to <<Data Registration (Data Model), data registrations>> and their corresponding <<Container (Access Logs from Data Model), containers>>.

.`ldp:Container` <<Thing>> at http://example.tld/dpc/data/74242fac/
[source,turtle]
----
include::resources/dump/model/dpc/data/74242fac/AccessLog/index.ttl[lines=13..14]
include::resources/dump/model/dpc/data/74242fac/AccessLog/index.ttl[lines=23..23]
----

NOTE: Followed Path [1,2,1]

== Verification (Data Model)

The verification resource shown in xref:wbs_Endpoint_structure[xrefstyle=short] is the only resource stored by the client and will be used for comparison purposes.
The verification code will be compared to the verification code of the <<Claim Registry (Data Model), claim registry>>.
If they are equivalent, access to the <<Container (Claimed Data from Data Model), claimed data>> will be granted.

.`claim:Verification` <<Thing>> at at http://example.tld/client/dpc
[source,turtle]
----
include::resources/dump/model/client/dpc$.ttl[]
----

NOTE: Followed Path [1,2,2]

Each of the mentioned resources must have a corresponding <<ACL>>.
The lists have been intentionally omitted for simplicity.
The <<DPC>> agent requires read and write access to all of these resources.
The only exception is the <<Verification (Data Model), verification resource>>, which only needs to be read.
