= Technology Stack

The technological stack is entirely based on ECMAScript respectively TypeScript.
Server-side scripts will be executed in the Node.js runtime environment, while client-side scripts will utilise the corresponding engine of the browser.

== Project Structure

The project was created as a multi-package repository, with `pnpm` footnote:[https://pnpm.io/] serving as the package manager for Node.js-based projects.
A multi-package repository is a repository that is used to group a variety of packages and artifacts that are maintained in a single repository.

The initial two levels of the project directory, including the packages contained within this project repository, are illustrated in xref:wbs-project-structure[xrefstyle=short].
Metadata directories and files are excluded from this diagram.
Node child packages are stored in the `./apps` directory, the `./packages` directory, and the `./tests/benchmark` directory.
These directories contain the source code for the experimental prototype.
The `./docs` directory contains all documents related to the research.
The `./scripts` directory contains custom build scripts that are used to produce the project's artifacts.
The `./tests/http` directory contains simple <<HTTP>> test files, which are used for singular tests.

.Structure diagram of the first two levels of the project directory.
[.text-center]
[plantuml,format=svg,id="wbs-project-structure"]
....
include::resources/diagrams/wbs_Project_structure.puml[]
....

The Node.js packages contained in the `./packages` folder are generic source code fragments utilized in the `./apps` packages.
The `./packages/core` folder contains the most basic data, which is used in nearly every package.
In contrast, the `./packages/ui` folder contains data relevant to the user interface or general view logic.
These packages are required by the `./apps/client` and `./apps/dpc` packages, as they represent applications that an actual user can interact with.
The `./apps/client` package can be used to test client requests, while the `./apps/dpc` package is used to view the monitoring data captured by the <<DPC>> middleware.
The middleware, however, is part of the `./apps/proxy` package, which delegates the `./apps/server` package, a wrapper package for the <<CSS>>, to the Node.js process.
The `./tests/benchmark` package is a wrapper package for Apache JMeter, which is called from the Node.js process.

== Third-Party Software

A variety of packages are utilised in the experimental prototype, with two packages of particular significance for this study: the Community Solid Serverfootnote:[https://communitysolidserver.github.io/] and Inrupt JavaScript Client Librariesfootnote:[https://docs.inrupt.com/developer-tools/javascript/client-libraries/].

The *Community Solider Server* is a modular implementation of the Solid Protocol, which allows for a variety of configuration options due to its modularity.
With the exception of the configurations that must be changed for the <<Experiments>>, the default configurations have been applied, as generated by the Community Solider Server configuration generatorfootnote:[https://communitysolidserver.github.io/configuration-generator/v7/].
The configuration options that have a particular influence on the tested scenario are data management and account management options.
The data storage component of data management is configured as the file system by default, which may have an impact on performance due to the necessity of writing files to the hard drive.
Similarly, locks are stored in the file system and are used to prevent simultaneous write operations on the same resource.
The default authorization mechanism is <<WAC>>.
With regard to account management, it is important to note that suffixes are used as storage container <<URL,URLs>>, rather than subdomains.
Furthermore, account management includes the identity provider, which uses <<OIDC>>.
The complete configuration file can be accessed in xref:css_configuration[xrefstyle=short].

At the client side, the *Inrupt JavaScript Client Library* is used to access <<RDF>> resources in a uniformed way.
Consequently, it is almost impossible to use <<CSS>> vendor <<API,APIs>>.

The network protocol <<HTTP>> is employed for all operations in this research.
Security measures such as <<HTTPS>> are not considered in this analysis.
Similarly, the <<Solid Provider>> has not been tested in an isolated network with a proxy, which must be the only public-accessible instance for a secure run in production environments.
This potential issue has been tested with Dockerfootnote:[https://docs.docker.com/], but it did not affect the research scenario.
