= Solid-Based Extended Access Control and Traceability in Data-Driven Web-Based Systems
//Front matter
include::partials/Front_matter.adoc[]

ifdef::backend-html5[''']
ifndef::backend-html5[<<<]

[abstract]
.Abstract
--
{abstract}
--

ifdef::backend-html5[''']
ifndef::backend-html5[<<<]

This document is divided into five sections: the Introduction, Theoretical Framework, Design and Implementation, Analysis, and Reflection.
The <<Introduction>> will refine the research context, the terminology used in this document, and the related work in this research area.
Fundamental concepts, such as data sovereignty and recommended quality aspects, will be summarized in the <<Theoretical Framework>>.
The <<Design and Implementation>> section will explain the system design concept and the technological choices made.
The <<Analysis>> section will define the experimental conditions and validate them with the quality criteria described in the Theoretical Framework.
The <<Reflection>> section will discuss the considerations from the Introduction, describe future work, and conclude the overall research.

= Introduction

[partintro]
The introduction will define the research, introduce the terminology used, and demonstrate related work on this topic.
The <<Research, research>> chapter will begin with a motivating problem and objectives that define the interest in this research.
This chapter will also define the design of this research and the concept, including the requirements.
The <<Terminology, terminology>> chapter will explain general solid terms, the understanding of access monitoring, the system definitions, and the proxy design pattern.
A summary of the state of the art will be provided in the section on <<Related Work, related work>>.

== Research

The Solid Project is an RDF-based ecosystem that aims to achieve a decentralized web for individuals, social entities, or software.
The technology is still in development and not yet fully evolved.
The current version is missing some essential features required for production environments.
Ongoing research and development is being conducted to improve the ecosystem, resulting in the regular introduction of new features or Solid providers.

This thesis aims to develop and analyze a Solid-based application that aligns with the Solid ecosystem without enforcing it.
The application will enhance data privacy concerns, specifically in terms of data traceability and access control.
The goal is to increase visibility and track requested resources from parties within and beyond the ecosystem through logs and their representation.
These requests should be processed and made manipulatable to achieve better control over the exposed data.
All of these achievements should be established in a clear context and communicated through data APIs to ensure safety for new features and potential changes in Solid providers.

include::partials/chapter/Problem_Definition.adoc[leveloffset=+2]

include::partials/chapter/Objectives_and_Research_Interest.adoc[leveloffset=+2]

include::partials/chapter/Research_Design.adoc[leveloffset=+2]

include::partials/chapter/Concept_and_Requirements.adoc[leveloffset=+2]

== Terminology

This section provides definitions for the central terms used.
Basic terms will only be included in the abbreviation section or the glossary due to the limited scope of this section.

include::partials/chapter/Access_Control_and_Traceability.adoc[leveloffset=+2]

include::partials/chapter/System.adoc[leveloffset=+2]

include::partials/chapter/Proxy.adoc[leveloffset=+2]

== Related Work

include::partials/chapter/Related_Work.adoc[leveloffset=+2]

= Theoretical Framework

[partintro]
The theoretical framework is intended to serve as a foundation for the concepts and technologies that are the subject of the research.
One of the central aspects is the <<Solid Ecosystem>>, which will be explained in the first chapter.
The ecosystem comprises several elements, and in this chapter, in particular, the Solid Protocol, Solid Provider, Solid Application Interoperability, and its limitations will be presented.
The second chapter will refer to the concept of <<Data Sovereignty>> within the ecosystem.
In this context, the concept of data trustees, the strategies for data capturing and the verification of ownership will be explained.
Finally, the <<Quality Model>> will be demonstrated, which is necessary to perform an analysis of the system design and performance efficiency.

== Solid Ecosystem

The Solid Project is an RDF-based ecosystem that aims to achieve a decentralized web for individuals, social entities, or software.
The ecosystem comprises a number of specifications and associated technologies, which are primarily listed in the Solid Technical Reports.
The most fundamental specification is the <<Solid Protocol>>, also known as the core specification.
In addition to the core specification, the following sections will explain the role of <<Solid Provider,Solid Providers>> in enabling the protocol and the <<Solid Application Interoperability>> specification, which extends the protocol.

include::partials/chapter/Solid_Protocol.adoc[leveloffset=+2]

include::partials/chapter/Solid_Provider.adoc[leveloffset=+2]

include::partials/chapter/Solid_Application_Interoperability.adoc[leveloffset=+2]

include::partials/chapter/Limits_of_Solid.adoc[leveloffset=+2]

== Data Sovereignty

include::partials/chapter/Data_Trustee.adoc[leveloffset=+2]

include::partials/chapter/Data_Capturing_Strategies.adoc[leveloffset=+2]

include::partials/chapter/Ownership_Verification.adoc[leveloffset=+2]

== Quality Model

include::partials/chapter/System_Design_Quality.adoc[leveloffset=+2]

include::partials/chapter/Performance_Efficiency.adoc[leveloffset=+2]

= Design and Implementation

== System Design

=== Logical Topology

include::Topology.adoc[leveloffset=+2,tags=body]

=== Logical Data Model

include::Model.adoc[leveloffset=+2,tags=body]

=== System Behavior

include::Behavior.adoc[leveloffset=+2,tags=body]

== Technology

include::partials/chapter/Technology_Stack.adoc[leveloffset=+2]

include::partials/chapter/Limits_of_the_Technology_Stack.adoc[leveloffset=+2]

include::partials/chapter/Deviation_from_Specification.adoc[leveloffset=+2]

= Analysis

include::partials/chapter/Experiments.adoc[leveloffset=+1]

include::partials/chapter/Validation.adoc[leveloffset=+1]

= Reflection

== Discussion

== Futur Work

== Conclusion

Viewing and using requests to the web server was a task that was almost exclusively reserved for the operators or administrators of a service.
For the first time functions can be viewed and controlled by users, as they own the content or have sufficient rights.

include::partials/Appendix.adoc[]

include::partials/Back_matter.adoc[]
